// <auto-generated />
using System;
using Lab6.DbUtils;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab6.Migrations
{
    [DbContext(typeof(ProductServicingContext))]
    partial class ProductServicingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab6.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AddressTypeCode")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("AddressTypeCode");

                    b.HasIndex("CompanyId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            AddressDetails = "123 Tech Street",
                            AddressTypeCode = 1,
                            CompanyId = 1
                        },
                        new
                        {
                            AddressId = 2,
                            AddressDetails = "456 Business Ave",
                            AddressTypeCode = 2,
                            CompanyId = 2
                        });
                });

            modelBuilder.Entity("Lab6.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            CompanyDetails = "Leading tech solutions",
                            CompanyName = "TechCorp"
                        },
                        new
                        {
                            CompanyId = 2,
                            CompanyDetails = "Software development specialists",
                            CompanyName = "SoftSolutions"
                        });
                });

            modelBuilder.Entity("Lab6.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerTypeCode")
                        .HasColumnType("int");

                    b.Property<int?>("EndUserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerTypeCode");

                    b.HasIndex("EndUserId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CompanyId = 1,
                            CustomerDetails = "Regular customer details for TechCorp",
                            CustomerTypeCode = 1,
                            EndUserId = 1
                        },
                        new
                        {
                            CustomerId = 2,
                            CompanyId = 2,
                            CustomerDetails = "Premium customer details for SoftSolutions",
                            CustomerTypeCode = 2,
                            EndUserId = 2
                        });
                });

            modelBuilder.Entity("Lab6.Models.CustomerMachine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MachineId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.Property<string>("InstallationLocationAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineOtherDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MachineType")
                        .HasColumnType("int");

                    b.HasKey("MachineId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DistributorId");

                    b.HasIndex("MachineType");

                    b.ToTable("CustomerMachines");

                    b.HasData(
                        new
                        {
                            MachineId = 1,
                            CustomerId = 1,
                            DistributorId = 1,
                            InstallationLocationAddress = "123 Tech Street",
                            MachineDescription = "High-speed office printer",
                            MachineName = "Office Printer",
                            MachineOtherDetails = "Requires monthly maintenance",
                            MachineType = 1
                        },
                        new
                        {
                            MachineId = 2,
                            CustomerId = 2,
                            DistributorId = 2,
                            InstallationLocationAddress = "456 Business Ave",
                            MachineDescription = "High-resolution scanner",
                            MachineName = "Office Scanner",
                            MachineOtherDetails = "Requires quarterly maintenance",
                            MachineType = 2
                        });
                });

            modelBuilder.Entity("Lab6.Models.Distributor", b =>
                {
                    b.Property<int>("DistributorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistributorId"));

                    b.Property<string>("DistributorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherDistributorDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceVendorId")
                        .HasColumnType("int");

                    b.HasKey("DistributorId");

                    b.HasIndex("ServiceVendorId");

                    b.ToTable("Distributors");

                    b.HasData(
                        new
                        {
                            DistributorId = 1,
                            DistributorName = "Tech Distributors",
                            OtherDistributorDetails = "Expert in tech distribution",
                            ServiceVendorId = 1
                        },
                        new
                        {
                            DistributorId = 2,
                            DistributorName = "Global Distributors",
                            OtherDistributorDetails = "Worldwide distribution network",
                            ServiceVendorId = 2
                        });
                });

            modelBuilder.Entity("Lab6.Models.EndUser", b =>
                {
                    b.Property<int>("EndUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EndUserId"));

                    b.Property<string>("EndUserDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EndUserId");

                    b.ToTable("EndUser");

                    b.HasData(
                        new
                        {
                            EndUserId = 1,
                            EndUserDetails = "John Doe"
                        },
                        new
                        {
                            EndUserId = 2,
                            EndUserDetails = "Jane Smith"
                        });
                });

            modelBuilder.Entity("Lab6.Models.RefAddressType", b =>
                {
                    b.Property<int>("AddressTypeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressTypeCode"));

                    b.Property<string>("AddressTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressTypeCode");

                    b.ToTable("RefAddressType");

                    b.HasData(
                        new
                        {
                            AddressTypeCode = 1,
                            AddressTypeDescription = "Home"
                        },
                        new
                        {
                            AddressTypeCode = 2,
                            AddressTypeDescription = "Office"
                        });
                });

            modelBuilder.Entity("Lab6.Models.RefCustomerType", b =>
                {
                    b.Property<int>("CustomerTypeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerTypeCode"));

                    b.Property<string>("CustomerTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerTypeCode");

                    b.ToTable("RefCustomerTypes");

                    b.HasData(
                        new
                        {
                            CustomerTypeCode = 1,
                            CustomerTypeDescription = "Regular"
                        },
                        new
                        {
                            CustomerTypeCode = 2,
                            CustomerTypeDescription = "Premium"
                        });
                });

            modelBuilder.Entity("Lab6.Models.RefMachineType", b =>
                {
                    b.Property<int>("MachineType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MachineType"));

                    b.Property<string>("MachineTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MachineType");

                    b.ToTable("RefMachineTypes");

                    b.HasData(
                        new
                        {
                            MachineType = 1,
                            MachineTypeDescription = "Printer"
                        },
                        new
                        {
                            MachineType = 2,
                            MachineTypeDescription = "Scanner"
                        });
                });

            modelBuilder.Entity("Lab6.Models.RefServiceType", b =>
                {
                    b.Property<int>("ServiceTypeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceTypeCode"));

                    b.Property<string>("ServiceTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceTypeCode");

                    b.ToTable("RefServiceTypes");

                    b.HasData(
                        new
                        {
                            ServiceTypeCode = 1,
                            ServiceTypeDescription = "Maintenance"
                        },
                        new
                        {
                            ServiceTypeCode = 2,
                            ServiceTypeDescription = "Repair"
                        });
                });

            modelBuilder.Entity("Lab6.Models.Service", b =>
                {
                    b.Property<int>("ServiceTypeCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfService")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.Property<string>("OtherServiceDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceVendorId")
                        .HasColumnType("int");

                    b.HasKey("ServiceTypeCode");

                    b.HasIndex("DistributorId");

                    b.HasIndex("ServiceVendorId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceTypeCode = 1,
                            DateOfService = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorId = 1,
                            OtherServiceDetails = "Routine maintenance",
                            ServiceVendorId = 1
                        },
                        new
                        {
                            ServiceTypeCode = 2,
                            DateOfService = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorId = 2,
                            OtherServiceDetails = "Urgent repair",
                            ServiceVendorId = 2
                        });
                });

            modelBuilder.Entity("Lab6.Models.ServiceVendor", b =>
                {
                    b.Property<int>("ServiceVendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceVendorId"));

                    b.Property<string>("ServiceVendorDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceVendorId");

                    b.ToTable("ServiceVendors");

                    b.HasData(
                        new
                        {
                            ServiceVendorId = 1,
                            ServiceVendorDetails = "FastTech Service"
                        },
                        new
                        {
                            ServiceVendorId = 2,
                            ServiceVendorDetails = "GlobalTech Service"
                        });
                });

            modelBuilder.Entity("Lab6.Models.Address", b =>
                {
                    b.HasOne("Lab6.Models.RefAddressType", "AddressType")
                        .WithMany("Addresses")
                        .HasForeignKey("AddressTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lab6.Models.Company", "Company")
                        .WithMany("Addresses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddressType");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Lab6.Models.Customer", b =>
                {
                    b.HasOne("Lab6.Models.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lab6.Models.RefCustomerType", "CustomerType")
                        .WithMany("Customers")
                        .HasForeignKey("CustomerTypeCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lab6.Models.EndUser", "EndUser")
                        .WithMany("Customers")
                        .HasForeignKey("EndUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("CustomerType");

                    b.Navigation("EndUser");
                });

            modelBuilder.Entity("Lab6.Models.CustomerMachine", b =>
                {
                    b.HasOne("Lab6.Models.Customer", "Customer")
                        .WithMany("CustomerMachines")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lab6.Models.Distributor", "Distributor")
                        .WithMany("CustomerMachines")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lab6.Models.RefMachineType", "MachineTypeNavigation")
                        .WithMany("CustomerMachines")
                        .HasForeignKey("MachineType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Distributor");

                    b.Navigation("MachineTypeNavigation");
                });

            modelBuilder.Entity("Lab6.Models.Distributor", b =>
                {
                    b.HasOne("Lab6.Models.ServiceVendor", "ServiceVendor")
                        .WithMany("Distributors")
                        .HasForeignKey("ServiceVendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceVendor");
                });

            modelBuilder.Entity("Lab6.Models.Service", b =>
                {
                    b.HasOne("Lab6.Models.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab6.Models.RefServiceType", "ServiceType")
                        .WithMany("Services")
                        .HasForeignKey("ServiceTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lab6.Models.ServiceVendor", "ServiceVendor")
                        .WithMany("Services")
                        .HasForeignKey("ServiceVendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distributor");

                    b.Navigation("ServiceType");

                    b.Navigation("ServiceVendor");
                });

            modelBuilder.Entity("Lab6.Models.Company", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Lab6.Models.Customer", b =>
                {
                    b.Navigation("CustomerMachines");
                });

            modelBuilder.Entity("Lab6.Models.Distributor", b =>
                {
                    b.Navigation("CustomerMachines");
                });

            modelBuilder.Entity("Lab6.Models.EndUser", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Lab6.Models.RefAddressType", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Lab6.Models.RefCustomerType", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Lab6.Models.RefMachineType", b =>
                {
                    b.Navigation("CustomerMachines");
                });

            modelBuilder.Entity("Lab6.Models.RefServiceType", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Lab6.Models.ServiceVendor", b =>
                {
                    b.Navigation("Distributors");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
